/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int ELSE = 11;
  int EXTENDS = 12;
  int FALSE = 13;
  int IF = 14;
  int IMPORT = 15;
  int INSTANCEOF = 16;
  int INT = 17;
  int NEW = 18;
  int NULL = 19;
  int PACKAGE = 20;
  int PRIVATE = 21;
  int PROTECTED = 22;
  int PUBLIC = 23;
  int RETURN = 24;
  int STATIC = 25;
  int SUPER = 26;
  int THIS = 27;
  int TRUE = 28;
  int VOID = 29;
  int WHILE = 30;
  int PLUS = 31;
  int ASSIGN = 32;
  int DEC = 33;
  int EQUAL = 34;
  int NOT_EQUAL = 35;
  int GT = 36;
  int LESS = 37;
  int INC = 38;
  int LAND = 39;
  int BITWISE_AND = 40;
  int LE = 41;
  int GTE = 42;
  int LNOT = 43;
  int MINUS = 44;
  int STAR = 45;
  int CONDITIONAL = 46;
  int UNARY_COMP = 47;
  int DIV = 48;
  int REM = 49;
  int SHR = 50;
  int SHL = 51;
  int USHR = 52;
  int BITWISE_OR = 53;
  int LOR = 54;
  int BITWISE_XOR = 55;
  int PLUS_ASSIGN = 56;
  int MINUS_ASSIGN = 57;
  int STAR_ASSIGN = 58;
  int DIV_ASSIGN = 59;
  int REM_ASSIGN = 60;
  int BITWISE_AND_ASSIGN = 61;
  int BITWISE_OR_ASSIGN = 62;
  int BITWISE_XOR_ASSIGN = 63;
  int SHR_ASSIGN = 64;
  int USHR_ASSIGN = 65;
  int SHL_ASSIGN = 66;
  int LPAREN = 67;
  int RPAREN = 68;
  int LCURLY = 69;
  int RCURLY = 70;
  int LBRACK = 71;
  int RBRACK = 72;
  int SEMI = 73;
  int COMMA = 74;
  int DOT = 75;
  int IDENTIFIER = 76;
  int LETTER = 77;
  int DIGIT = 78;
  int NON_ZERO_DIGIT = 79;
  int INT_LITERAL = 80;
  int CHAR_LITERAL = 81;
  int STRING_LITERAL = 82;
  int ESC = 83;
  int ERROR = 84;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"++\"",
    "\"&&\"",
    "\"&\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"-\"",
    "\"*\"",
    "\"?\"",
    "\"~\"",
    "\"/\"",
    "\"%\"",
    "\">>\"",
    "\"<<\"",
    "\">>>\"",
    "\"|\"",
    "\"||\"",
    "\"^\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
